### PR TITLE
Update to RGB Matrix LED structure

### PR DESCRIPTION
**Pull request by drashna**
This changes the rgb LED structure to allow for much more customized effects.  

This is not all of it, just the start of the code changes.  

It may be best to leave this alone until the rest of the code changes are present. 

~~However, Travis CI fails due to the reactive keymap being too large. (the reactive keymap has all reactive modes enabled, which .... is a LOT)~~

### CODE REVIEW

**Comment by drashna** [comment]
Rebasing reduced thee file size, so Travis CI no longer fails

**Comment by drashna** [comment]
@fdidron just making sure, you're holding off on this, because of the significant change to the rgb matrix structure, correct? 

If so, that's fine, and there is qmk#5783 that we may want to wait on, to merge at the same time. 

It's not an insignificant change, but should further optimize the rgb matrix code.

**Comment by fdidron** [comment]
@drashna exactly, thought I would hold until the rest of the changes are merged.

**Comment by drashna** [comment]
There is actually one more PR that I'd like to wait on before this gets merged.  qmk#5811 optimizes a number of things here, too.

**Comment by drashna** [comment]
This is ready to ship!

**Pull request merged**
