### PR TITLE
Make moonlander layer LEDs follow a binary sequence

### PR DESCRIPTION
**Pull request by kwmlodozeniec**
Currently, the moonlander layer LEDs do not follow a sensible pattern. The ZSA website states this keyboard supports up to 32 layers so I thought making the LEDs follow a binary sequence would accommodate that. This PR achieves that, but I am not sure if this is the best way to represent it. Code builds fine but I have not rested it on a keyboard.

### CODE REVIEW

**Comment by drashna** [comment]
I'm not sure that binary is the best way to go about this, to be honest, as many people may not be familiar with it. 

Additionally, the code you've added is incredibly verbose, and can be simplified.  In fact, all of that should be able to be broken down to just this: 
```c
layer_state_t layer_state_set_kb(layer_state_t state) {
    state         = layer_state_set_user(state);
    if (is_launching || !keyboard_config.led_level) return state;

    ML_LED_1(state & 0b000001);
    ML_LED_2(state & 0b000010);
    ML_LED_3(state & 0b000100);
    ML_LED_4(state & 0b001000);
    ML_LED_5(state & 0b010000);
    ML_LED_6(state & 0b100000);

    return state;
}

**Comment by kwmlodozeniec** [comment]
Indeed, binary is not common knowledge. Maybe there could be two modes. One for up to 6 layers, each LED corresponding to a layer, and another, binary, for up to 32 as advertised.

With regards to code, very good point and I have considered making it less verbose but the current implementation is also verbose so I followed the same style for consistency.

**Comment by drashna** [comment]
2 modes would probably be best, I think, hidden with a define, maybe.

**Comment by dirk-bester** [comment]
Why not a color sequence and 1 to 6 led lit up in each

**Pull request closed without merging**
