### PR TITLE
Add macro for defining LED layouts on ergodox_ez glow

### PR DESCRIPTION
**Pull request by dmsnell**
While working on a custom layout for my EZ Glow I didn't see a way to visually identify LED colors per-key using an array-per-layer so I created a macro in `glow.h` based on the keymap macros. Of note the visual map only includes the keys with LEDs and so it doesn't match the layout alignments/visuals.

If there's interest in merging this PR I can recreate the other layout macros in similar fashion for the LEDs, the `_80`, `_pretty_80`, and un-suffixed versions. Also I'm happy to do any other work necessary to prep this PR.

**Config Before**

```c
const uint8_t PROGMEM ledmap[][DRIVER_LED_TOTAL][1] = {
    /* Key map is reversed for left hand
      6     7     8     9     0
      Y     U     I     O     P
      H     J     K     L     ;
      N     M     ,     .     /
            UP    DN    [     ]

      5     4     3     2     1
      T     R     E     W     Q
      G     F     D     S     A
      B     V     C     X     Z
            RGT   LFT   ORYX  "
     */
     [0] = {
       ___,  ___,  ___,  ___,  ___,
       _RED, _BLU, _BLU, _BLU, _YLW,
       _RED, _BLU, _BLU, _BLU, _YLW,
       _YLW, _BLU, _BLU, _BLU, _YLW,
             _BLU, _BLU, _YLW, _YLW,

       ___,  ___,  ___,  ___,  ___,
       ___,  _RED, _RED, _BLU, ___,
       ___,  _YLW, _YLW, ___,  _BLU,
       ___,  _GRN, _GRN, ___,  _BLU,
             ___,  ___,  ___,  ___
     }
};
```

**Config After**

```c
const uint8_t PROGMEM ledmap[][DRIVER_LED_TOTAL][1] = {
    [0] = LED_LAYOUT_ergodox_pretty(
      ___,  ___,  ___,  ___,  ___,        ___,  ___,  ___,  ___,  ___,
      ___,  _BLU, _RED, _RED, ___,        _RED, _BLU, _BLU, _BLU, _YLW,
      _BLU, ___,  _YLW, _YLW, ___,        _RED, _BLU, _BLU, _BLU, _YLW,
      _BLU, ___,  _GRN, _GRN, ___,        _YLW, _BLU, _BLU, _BLU, _YLW,
      ___,  ___,  ___,  ___,                    _BLU, _BLU, _YLW, _YLW
    )
}
```

### CODE REVIEW

**Comment by dmsnell** [comment]
Is there any thought on this PR? Can someone at least indicate if it's something I should keep open or close?

**Comment by drashna** [comment]
If anything, this should be applied to the main ergodox ez file, not the glow, specifically.

**Comment by dmsnell** [comment]
> this should be applied to the main ergodox ez file

good call, @drashna - I've moved it there and rebased

**Comment by drashna** [comment]
Also, could you retarget this for firmware20, or firmware21 (ideally)

**Comment by dmsnell** [comment]
@drashna rebased and re-targeted to `firmware21`

**Review by drashna — APPROVED** [review]

**Comment by dmsnell** [comment]
Thanks @drashna - hope someone finds this useful.

**Comment by ghost** [comment]
I've found this helpful in hand-coding ledmaps: Thanks for persisting. 

With the addition of a collection of color definitions all having the same number of characters, it makes for a map that is easy to read and maintain.

**Pull request merged**
